### ISSUE TITLE
Undeclared dependencies

### ISSUE THREAD

**Issue by eserte** [jplindstrom/p5-autobox-Transform#1]
A number of prereqs are not declared: true, autobox, autbox::Core.
See also 
http://analysis.cpantesters.org/solved?distv=autobox-Transform-1.001#qr%3A%28Can%27t%20locate%20\S%2Bpm%29

**Comment by jplindstrom** [comment]
Ah, thanks!

I just started using Minilla and forgot you need a cpanfile for that.
