### ISSUE TITLE
Fails with perls < 5.10

### ISSUE THREAD

**Issue by andk** [jplindstrom/p5-autobox-Transform#2]
As per subject. Best illustrated with the matrix: 

http://matrix.cpantesters.org/?dist=autobox-Transform+1.008

Sample fail report: 

http://www.cpantesters.org/cpan/report/9e6e6a24-2a75-11e6-8805-ea80c46c58f4

If this is intentional, it would be cool if you could declare your requirement. That way the FAILS are converted to UNKNOWNS. Details about how to do it are on this page: http://wiki.cpantesters.org/wiki/CPANAuthorNotes

Let me know if you need further information.

HTH&&Thanks,

**Comment by jplindstrom** [comment]
The latest release 1.012 which is on CPAN now should have this fixed.

It took a while to figure out how to do it with Minilla, but it turned out to be to simply declare it in the module itself.
