### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by findmo** [jplindstrom/p5-autobox-Transform#3]
currently get 'Needs perl 5.10, you have 5.016003' when trying to install.

you may need to change 'use v5.10;' to 'use  5.010'.

**Comment by jplindstrom** [comment]
Sorry for ignoring this, I don't think I get email notifications properly (have tried to fix that in settings).

I just released a new version 1.013, which is on its way across the mirrors of CPAN now.

Please reopen this ticket if you still have problems installing the module.
